# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Site description.
# host: 192.168.1.144
baseurl: "/ChoiceScapes" # the subpath of your site, e.g. /blog/
url: "http://akajut.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

exclude: [vendor]
